import type { DefaultTheme } from "vitepress";

// This file is auto-generated by scripts/generate-sidebar.mjs.
// Do not edit manually.
type SidebarItemWithCollapsible = Omit<DefaultTheme.SidebarItem, "items"> & {
	collapsible?: boolean;
	items?: SidebarItemWithCollapsible[];
};

export const sidebar: SidebarItemWithCollapsible[] = [
	{
		text: "Vue",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Vue", link: "/vue" },
			{ text: "Директивы Vue", link: "/vue/direktivy-vue" },
			{ text: "Зачем вообще нужен", link: "/vue/scheduler" },
			{ text: "Основные хуки во", link: "/vue/zhiznennye-tsikly-komponentov-vue-2-vs-vue-3" },
			{ text: "Подкапотные темы Vue.js", link: "/vue/podkapotnye-temy-vo-vue-js" },
			{ text: "Рендер-функции", link: "/vue/render-funktsii" },
			{ text: "Типичный стек хайлоад", link: "/vue/optimizatsiya-high-load-proekta" },
			{ text: "defineExpose", link: "/vue/defineexpose" },
			{ text: "nextTick что это", link: "/vue/asinkhronnye-rendery-i-batching" },
			{ text: "Pinia", link: "/vue/pinia" },
			{ text: "provide и inject", link: "/vue/provide-i-inject" },
			{ text: "Suspense", link: "/vue/suspense" },
			{ text: "Template под капотом", link: "/vue/template-pod-kapotom" },
			{ text: "Tree-Shaking", link: "/vue/tree-shaking" },
			{ text: "Virtual DOM", link: "/vue/virtual-dom" },
			{ text: "watch vs watchEffect", link: "/vue/watch-i-watcheffect" },
			{
				text: "Задачи",
				collapsible: true,
				collapsed: true,
				items: [
					{ text: "Двустороннее связывание через", link: "/vue/zadachi/dvustoronnee-svyazyvanie-cherez-v-model" },
					{ text: "Props и Emits", link: "/vue/zadachi/propsy-emity" }
				],
			},
			{
				text: "Ref & reactive",
				collapsible: true,
				collapsed: true,
				items: [
					{ text: "Что делает каждый", link: "/vue/ref-and-reactive/reaktivnost-vo-vue3" },
					{ text: "reactive", link: "/vue/ref-and-reactive/reactive" },
					{ text: "ref vs reactive", link: "/vue/ref-and-reactive/ref-vs-reactive" },
					{ text: "shallowReactive", link: "/vue/ref-and-reactive/shallowreactive" },
					{ text: "shallowRef", link: "/vue/ref-and-reactive/shallowref" }
				],
			}
		],
	},
	{
		text: "React",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "React", link: "/react" },
			{ text: "Локальное состояние в", link: "/react/lokalnoe-sostoyanie-reaktivnost" },
			{ text: "Чит-щит сводная таблица", link: "/react/tablitsa-sravneniya-react-vs-vue" },
			{ text: "JSX и его", link: "/react/jsx-i-ego-alternativy" },
			{ text: "React примере Vue", link: "/react/react-na-primere-vue" },
			{ text: "React vs Vue", link: "/react/osnovnye-funktsii-react" },
			{ text: "UseState подробно", link: "/react/usestate-podrobno" },
			{
				text: "Хуки",
				collapsible: true,
				collapsed: true,
				items: [
					{ text: "Основные хуки React", link: "/react/khuki/osnovnye-khuki-v-react" },
					{ text: "useContext", link: "/react/khuki/usecontext" },
					{ text: "useEffect", link: "/react/khuki/useeffect" },
					{ text: "useState", link: "/react/khuki/usestate" }
				],
			}
		],
	},
	{
		text: "Архитектура",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Архитектура", link: "/arkhitektura" },
			{ text: "1️⃣ Layered Architecture", link: "/arkhitektura/top-5-frontend-arkhitektur" },
			{ text: "Микросервисы", link: "/arkhitektura/mikroservisy" },
			{ text: "Микрофронтенд", link: "/arkhitektura/mikrofrontend" },
			{ text: "Монолит", link: "/arkhitektura/monolit" },
			{ text: "Структура проекта быстро", link: "/arkhitektura/shpargalka-po-arkhitekturam" },
			{ text: "Трассировка запросов Request", link: "/arkhitektura/trassirovka-zaprosov-opentelemetry" },
			{ text: "Уровни Слои FSD", link: "/arkhitektura/feature-sliced-design" },
			{ text: "Циклические зависимости избежать", link: "/arkhitektura/tsiklicheskie-zavisimosti" },
			{ text: "Что такое архитектура", link: "/arkhitektura/arkhitektura-prilozhenii-vidy-i-osobennosti" },
			{ text: "Что такое DDD", link: "/arkhitektura/domain-driven-design" }
		],
	},
	{
		text: "JavaScript",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Как работает JS", link: "/javascript/kak-rabotaet-javascript-pod-kapotom" },
			{ text: "Методы массивов", link: "/javascript/metody-massivov" },
			{ text: "Операторы", link: "/javascript/operatory" },
			{ text: "Типы функций", link: "/javascript/tipy-funktsii" },
			{ text: "Условные операторы", link: "/javascript/uslovnye-operatory" },
			{ text: "Что такое замыкание", link: "/javascript/chto-takoe-zamykanie" },
			{ text: "Event Bubbling", link: "/javascript/event-bubbling" },
			{ text: "Event Loop", link: "/javascript/event-loop" },
			{ text: "JSON и его", link: "/javascript/json-i-ego-alternativy" },
			{ text: "Object.freeze", link: "/javascript/object-freeze" },
			{ text: "Promise", link: "/javascript/promise" },
			{
				text: "Коллекции данных",
				collapsible: true,
				collapsed: true,
				items: [
					{ text: "Map", link: "/javascript/kollektsii-dannykh/map" },
					{ text: "Set", link: "/javascript/kollektsii-dannykh/set" },
					{ text: "WeakMap", link: "/javascript/kollektsii-dannykh/weakmap" },
					{ text: "WeakSet", link: "/javascript/kollektsii-dannykh/weakset" }
				],
			},
			{
				text: "Типы данных",
				collapsible: true,
				collapsed: true,
				items: [
					{ text: "Типы данных", link: "/javascript/tipy-dannykh/tipy-dannykh" },
					{ text: "Object", link: "/javascript/tipy-dannykh/object" }
				],
			}
		],
	},
	{
		text: "HTML",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Семантические теги", link: "/html/semanticheskie-tegi" },
			{ text: "Shadow DOM", link: "/html/shadow-dom" }
		],
	},
	{
		text: "CSS",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Адаптивная и отзывчивая", link: "/css/adaptivnaya-i-otzyvchivaya-verstka" },
			{ text: "Позиционирование в CSS", link: "/css/pozitsionirovanie-v-css" },
			{ text: "Расположение контента на", link: "/css/raspolozhenie-kontenta-i-vysota-main" },
			{ text: "Центрирование в CSS", link: "/css/tsentrirovanie-v-css" },
			{ text: "will-change", link: "/css/will-change" },
			{ text: "z-index и stacking", link: "/css/z-index-i-stacking-context" }
		],
	},
	{
		text: "TypeScript",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "TS", link: "/typescript" },
			{ text: "Утилитарные типы", link: "/typescript/utilitarnye-tipy" },
			{ text: "Шпоры TS", link: "/typescript/shpory-ts" },
			{ text: "as const в", link: "/typescript/as-const-v-typescript" },
			{ text: "assert в TS", link: "/typescript/assert-v-typescript" },
			{ text: "satisfies в TS", link: "/typescript/satisfies-v-typescript" },
			{ text: "Type Guards виды", link: "/typescript/taypguardy-v-typescript" },
			{
				text: "Задачи",
				collapsible: true,
				collapsed: true,
				items: [
					{ text: "Задача реализовать Pick", link: "/typescript/zadachi/zadacha-realizovat-pick-svoimi-silami" }
				],
			}
		],
	},
	{
		text: "Nuxt",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Nitro", link: "/nuxt/nitro" },
			{ text: "Nuxt vs Vue", link: "/nuxt/nuxt-vs-vue" },
			{ text: "Nuxt2 vs Nuxt3", link: "/nuxt/nuxt2-vs-nuxt3" },
			{
				text: "Режимы рендера",
				collapsible: true,
				collapsed: true,
				items: [
					{ text: "Hydration", link: "/nuxt/rezhimy-rendera/hydration" },
					{ text: "ISR ISR", link: "/nuxt/rezhimy-rendera/isr-incremental-static-regeneration" },
					{ text: "SSG SSG", link: "/nuxt/rezhimy-rendera/ssg-static-site-generation" },
					{ text: "SSR SSR", link: "/nuxt/rezhimy-rendera/ssr-server-side-rendering" }
				],
			}
		],
	},
	{
		text: "Браузеры",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Браузеры", link: "/brauzery" },
			{ text: "База что такое", link: "/brauzery/mezhdomennye-zaprosy-cors-jsonp-proxy" },
			{ text: "Зачем нужно общение", link: "/brauzery/obschenie-mezhdu-vkladkami-brauzera" },
			{ text: "Зачем нужны Workers", link: "/brauzery/workers-v-brauzere" },
			{ text: "Оптимизация изображений в", link: "/brauzery/optimizatsiya-izobrazhenii-v-vebe" },
			{ text: "происходит когда пользователь", link: "/brauzery/polnyi-put-zagruzki-saita" },
			{ text: "Сети HTTP и", link: "/brauzery/seti-http-i-cors" },
			{ text: "Что такое SSE", link: "/brauzery/server-sent-events-sse" },
			{ text: "A11y Accessibility", link: "/brauzery/a11y-accessibility" },
			{ text: "Forced Synchronous Layout", link: "/brauzery/forced-synchronous-layout-i-long-tasks" },
			{ text: "LCP INP TTI", link: "/brauzery/lcp-inp-tti" },
			{ text: "Reflow Repaint и", link: "/brauzery/reflow-repaint-i-layout-thrashing" },
			{ text: "WebSocket в браузере", link: "/brauzery/websockety-v-brauzere" },
			{
				text: "Версии HTTP",
				collapsible: true,
				collapsed: true,
				items: [
					{ text: "Сравнение HTTP версий", link: "/brauzery/versii-http/sravnenie-http-versii" },
					{ text: "HTTP/1.1", link: "/brauzery/versii-http/http-1-1" },
					{ text: "HTTP/2", link: "/brauzery/versii-http/http-2" },
					{ text: "HTTP/3", link: "/brauzery/versii-http/http-3" }
				],
			},
			{
				text: "CRP",
				collapsible: true,
				collapsed: true,
				items: [
					{ text: "Типичные ошибки в", link: "/brauzery/crp/oshibki-critical-render-path" },
					{ text: "Critical Render Path", link: "/brauzery/crp/critical-render-path" }
				],
			},
			{
				text: "Garbage Collector",
				collapsible: true,
				collapsed: true,
				items: [
					{ text: "Сборщик мусора", link: "/brauzery/garbage-collector/1-sborschik-musora" },
					{ text: "Утечки памяти", link: "/brauzery/garbage-collector/2-utechki-pamyati" },
					{ text: "Частые вопросы", link: "/brauzery/garbage-collector/voprosy-po-garbage-collector" }
				],
			}
		],
	},
	{
		text: "Безопасность",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "безопасность приложений", link: "/bezopasnost-prilozhenii/bezopasnost-prilozhenii" },
			{ text: "Что такое CSRF", link: "/bezopasnost-prilozhenii/csrf-cross-site-request-forgery" },
			{ text: "Что такое XSS", link: "/bezopasnost-prilozhenii/xss-cross-site-scripting" },
			{ text: "CSP CSP", link: "/bezopasnost-prilozhenii/csp-content-security-policy" }
		],
	},
	{
		text: "Авторизация",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Авторизация", link: "/avtorizatsiya/avtorizatsiya" },
			{ text: "Cookie-сессия vs JWT", link: "/avtorizatsiya/cookie-sessiya-vs-jwt" },
			{ text: "JWT", link: "/avtorizatsiya/jwt" }
		],
	},
	{
		text: "Алгоритмы",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Алгоритмы", link: "/algoritmy/algoritmy" },
			{ text: "Карта по алгосам", link: "/algoritmy/karta-po-algosam" },
			{ text: "Структуры данных", link: "/algoritmy/2-struktury-dannykh" }
		],
	},
	{
		text: "ООП",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "ООП", link: "/oop" },
			{ text: "Пораждающие паттерны", link: "/oop/porazhdayuschie-patterny" },
			{ text: "Принципы", link: "/oop/printsipy-oop" }
		],
	},
	{
		text: "npm tools",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Генерация API-клиентов", link: "/npm-tools/openapi-swagger-protobuf" },
			{ text: "gRPC и Protobuf", link: "/npm-tools/grpc-i-protobuf" },
			{ text: "NaiveUI", link: "/npm-tools/naiveui" },
			{ text: "Nx и Turborepo", link: "/npm-tools/nx-i-turborepo" }
		],
	},
	{
		text: "Pixi",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Pixi по темам", link: "/pixi-po-temam" },
			{ text: "Глубокое понимание PixiJS", link: "/pixi-po-temam/1-glubokoe-ponimanie-pixijs" },
			{ text: "Карта по Pixi", link: "/pixi-po-temam/karta-po-pixi" },
			{ text: "Производительность и отладка", link: "/pixi-po-temam/4-proizvoditelnost-i-otladka" },
			{ text: "Pixi", link: "/pixi-po-temam/pixi" },
			{ text: "TS-first в Pixi", link: "/pixi-po-temam/3-typescript-first" },
			{ text: "Vue 3 Pixi", link: "/pixi-po-temam/2-vue-3-plus-pixi-patterny-integratsii" }
		],
	},
	{
		text: "Принципы программирования",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Принципы программирования", link: "/printsipy-programmirovaniya" },
			{ text: "Маленькие принципы", link: "/printsipy-programmirovaniya/malenkie-printsipy" },
			{ text: "SOLID", link: "/printsipy-programmirovaniya/solid" }
		],
	},
	{
		text: "Кэширование",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Кэширование", link: "/keshirovanie" },
			{ text: "Кэш", link: "/keshirovanie/kesh" }
		],
	},
	{
		text: "Задачи",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Задачи", link: "/zadachi" },
			{ text: "Подготовка к собеседованию", link: "/podgotovka-k-sobesedovaniyu" },
			{
				text: "Яндекс",
				collapsible: true,
				collapsed: true,
				items: [
					{ text: "1 этап", link: "/zadachi/yandeks/1-etap" }
				],
			}
		],
	},
	{
		text: "Сборщики",
		collapsible: true,
		collapsed: true,
		items: [
			{
				text: "Vite",
				collapsible: true,
				collapsed: true,
				items: [
					{ text: "Vite", link: "/sborschiki/vite/vite" }
				],
			}
		],
	},
	{
		text: "Тестирование",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "эти три инструмента", link: "/testirovanie/vitest-plus-vue-test-utils-plus-playwright" },
			{ text: "Vitest", link: "/testirovanie/vitest" }
		],
	}
];
